spring:
  application:
    name: lingflow-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: lingflow
    password: lingflow
    driver-class-name: org.postgresql.Driver
  
  # Flowable配置
  flowable:
    database-schema-update: true
    async-executor-activate: true
    mail:
      server:
        host: smtp.example.com
        port: 25

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingflow.entity
  type-handlers-package: com.lingflow.config
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

logging:
  level:
    #root: INFO
    org.springframework.web: DEBUG
    #org.flowable: DEBUG
    com.lingflow: DEBUG
    com.lingflow.repository: DEBUG
    org.springframework.boot.autoconfigure.logging: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
